name: Crave Builder
on:
  workflow_dispatch:
    # Various inputs to simplify usage of workflow.
    inputs:
      BASE_PROJECT:
        description: 'Choose a base project:'
        required: true
        default: 'LineageOS 20.0'
        type: choice
        options:
          - 'LineageOS 20.0'
          - 'LineageOS 21.0'
      REMOVALS:
        description: "Folders to be removed before syncing:"
        required: false
      JSON_AS_VAR:
        description: "All variable"
        required: false
      DEVICE_NAME:
        description: "Device's codename:"
        required: true
        default: "a03s"
      PRODUCT_NAME:
        description: "Product to build:"
        required: true
        default: "lineage_a03s"
      BUILD_COMMAND:
        description: 'Command to be used for compiling:'
        required: true
        default: 'mka bacon -j$(nproc --all)'
      BUILD_TYPE:
        description: 'Type of build:'
        required: true
        default: 'userdebug'
        type: choice
        options: 
        - 'eng'
        - 'userdebug'
        - 'user' 
      CLEAN_BUILD:
        description: 'Build with a clean workspace?'
        required: true
        default: 'no'
        type: choice
        options: 
        - 'yes'
        - 'no'

env:
  JSON_INPUT: ${{ github.event.inputs.JSON_AS_VAR }}

jobs:
  test:
    name: Build using foss.crave.io
      # Change this to self-hosted after setting up devspace as github actions runner
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:

    # Create a project folder
    - name: Create Project Folders
      run: |
        if [ "${DCDEVSPACE}" != "1" ]; then
          echo "Symlinking devspace folder"
          mkdir -p devspace
          sudo mkdir -p /crave-devspaces
          sudo ln -sf ${pwd}/devspace /crave-devspaces
          sudo chmod 777 /crave-devspaces
        else
          echo "We are already running in devspace... Skipping Symlinks"
        fi
        case "${{ github.event.inputs.BASE_PROJECT }}" in3
        "LineageOS 21.0")
          export PROJECTFOLDER="/crave-devspaces/Lineage21"
        ;;
        "LineageOS 20.0")
          export PROJECTFOLDER="/crave-devspaces/Lineage20"
        ;;
        esac
        if [ -d "$PROJECTFOLDER" ]; then
          echo "$PROJECTFOLDER directory exists, skipping..."
        else
          mkdir $PROJECTFOLDER
        fi
        echo "PROJECTFOLDER=$PROJECTFOLDER" >> "$GITHUB_ENV"

    # Check-out in order to access the repository's files.
    - name: Check-out to repository
      uses: actions/checkout@v4

    # Set-up a spearate directory for the device.
    - name: Set-up workspace environment
      run: |
        mkdir ${{ github.event.inputs.DEVICE_NAME }}
        cd ${{ github.event.inputs.DEVICE_NAME }}
      continue-on-error: true

    # Download and configure 'repo'.
    - name: Configure the 'repo' environment
      run: |
        # Check if repo is already installed
        if ! command -v repo >/dev/null 2>&1; then
          echo "Repo not found. Installing now..."
          # Create bin directory if it doesn't exist
          mkdir -p ~/bin
          # Download repo script
          curl https://storage.googleapis.com/git-repo-downloads/repo >> ~/bin/repo
          # Make repo script executable
          chmod a+x ~/bin/repo
          # Create symbolic link to /usr/bin/repo
          sudo ln -sf "/home/$(whoami)/bin/repo" "/usr/bin/repo"
          echo "Repo installation complete."
        else
          echo "Repo already installed."
        fi
      continue-on-error: true

    # Generate 'git' credential in base of the workflow's author.
    - name: Set-up 'git' credential(s)
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

    # Initialize the previously choosen 'repo' project.
    - name: Set the 'crave' project
      run: |
        cd $PROJECTFOLDER
        case "${{ github.event.inputs.BASE_PROJECT }}" in
          "LineageOS 21.0")
            repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1
          ;;
          "LineageOS 20.0")
            repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs --depth=1
          ;;
        esac

    - name: set inputs as variables
      run: |
        echo -e "DEVICE_TREE_URL=$(echo $JSON_INPUT | jq ".DEVICE_TREE_URL")" >> $GITHUB_ENV
        echo -e "DEVICE_TREE_BRANCH=$(echo $JSON_INPUT | jq ".DEVICE_TREE_BRANCH")" >> $GITHUB_ENV
        echo -e "DEVICE_TREE_LOCATION=$(echo $JSON_INPUT | jq ".DEVICE_TREE_LOCATION")" >> $GITHUB_ENV
        echo -e "VENDOR_TREE_URL=$(echo $JSON_INPUT | jq ".VENDOR_TREE_URL")" >> $GITHUB_ENV
        echo -e "VENDOR_TREE_BRANCH=$(echo $JSON_INPUT | jq ".VENDOR_TREE_BRANCH")" >> $GITHUB_ENV
        echo -e "VENDOR_TREE_LOCATION=$(echo $JSON_INPUT | jq ".DEVICE_TRRE_LOCATION")" >> $GITHUB_ENV
      
    # Setup SSH Key
    - name: Setup SSH Keys
      if: ${{ startsWith(env.DEVICE_TREE_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
    
    # Clone specified device tree
    - name: Clone device tree
      run: |
        cd $PROJECTFOLDER
        git clone ${{ env.DEVICE_TREE_URL }} -b ${{ env.DEVICE_TREE_BRANCH }} ./${{ env.DEVICE_TREE_LOCATION }}

    # Clone specified vendor tree
    - name: Clone vendor tree
      run: |
        cd $PROJECTFOLDER
        git clone ${{ env.VENDOR_TREE_URL }} -b ${{ env.VENDOR_TREE_BRANCH }} ./${{ env.VENDOR_TREE_LOCATION }}

    # Create a 'crave' job for building.
    - name: Start compilation through 'crave'
      run: |
        cd $PROJECTFOLDER

        if [ "${{ github.event.inputs.CLEAN_BUILD }}" == "yes" ]; then
          crave run --no-patch --clean "rm -rf .repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} && \
        else
        crave run --no-patch "rm -rf .repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} && \
        fi

        # Sync the repositories
        /opt/crave/resync.sh  && \

        # Set up build environment
        export BUILD_USERNAME=${{ github.actor }} ; \
        export BUILD_HOSTNAME=crave ; \
        source build/envsetup.sh && \

        # Build the ROM
        lunch ${{ github.event.inputs.PRODUCT_NAME }}-${{ github.event.inputs.BUILD_TYPE }} && \
        make installclean && \
        ${{ github.event.inputs.BUILD_COMMAND }}"


    # Only reach this wheter the user killed the workflow.
    - name: Execute if the job is cancelled
      if: ${{ cancelled() }}
      run: |
        cd $PROJECTFOLDER
        crave stop --all

    # Pull '.zip's and '.img's from 'crave'.
    - name: Retrive build artifact(s)
      run: |
        cd $PROJECTFOLDER
        crave ssh -- sleep 1
        crave pull out/target/product/*/*.zip
        crave pull out/target/product/*/*.img

    # Directly upload to releases.
    - name: Upload to repository's releases page
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.PROJECTFOLDER }}/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
          ${{ env.PROJECTFOLDER }}/${{ github.event.inputs.DEVICE_NAME }}/boot.img
          ${{ env.PROJECTFOLDER }}/${{ github.event.inputs.DEVICE_NAME }}/vendor_boot.img
          ${{ env.PROJECTFOLDER }}/${{ github.event.inputs.DEVICE_NAME }}/vendor.img
          ${{ env.PROJECTFOLDER }}/${{ github.event.inputs.DEVICE_NAME }}/system.img
          ${{ env.PROJECTFOLDER }}/${{ github.event.inputs.DEVICE_NAME }}/*.zip
        name: ${{ github.event.inputs.PRODUCT_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Target: ${{ github.event.inputs.PRODUCT_NAME }}-${{ github.event.inputs.BUILD_TYPE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECTFOLDER: ${PROJECTFOLDER}
